version: "3"
services:
    api:
        container_name: phisical-computing-api
        build: .
        depends_on:
            - db
        environment:
            DATABASE_URL: ${DATABASE_URL}
        ports:
            - "5001:5001"
        restart: unless-stopped
        volumes:
            - ./src:/code/src
    db:
        container_name: phisical-computing-db
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: phisical_computing
            POSTGRES_USER: phisical_computing
            POSTGRES_PASSWORD: STRONG_DB_PASSWORD
        restart: unless-stopped
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    db_data:
